In [1]:
import numpy as np

In [14]:
Y=np.empty([2,2],np.int32)
print(Y)

[[97976354        0]
 [ 7050404        0]]


In [6]:
X=np.eye(3)

In [7]:
print(X)

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [18]:
np.zeros_like(Y)

array([[0, 0],
       [0, 0]])

In [19]:
np.ones([3,2],float)

array([[ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.]])

In [27]:
R=np.arange(-5,4,1, dtype=np.int64)
np.ones_like(R)

array([1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64)

In [30]:
np.zeros([3,2],np.float64)

array([[ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.]])

In [33]:
x = np.arange(4, dtype=np.int64)
np.zeros_like(x)

array([0, 0, 0, 0], dtype=int64)

In [39]:
np.full((2,5),6,np.uint)

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]], dtype=uint32)

In [41]:
Y=np.full((2,5),6,np.uint)
np.ones_like(Y)*6

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]], dtype=uint32)

In [45]:
np.arange(1,4,dtype=np.int32)

array([1, 2, 3])

In [46]:
x = [1,2]
np.array(x,np.int32)

array([1, 2])

In [47]:
X = np.array([[1, 2], [3, 4]])
np.matrix(X,np.int32)

matrix([[1, 2],
        [3, 4]])

In [48]:
x = [1, 2]
np.array(x,np.float64)

array([ 1.,  2.])

In [53]:
x = np.array([30])
np.asscalar(x)

30

In [56]:
x = np.array([1, 2, 3])
y=np.copy(x)
print (id(x),x)
print (id(y),y)

121518880 [1 2 3]
121517520 [1 2 3]


In [58]:
np.arange(-10,10,1)

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,
         3,   4,   5,   6,   7,   8,   9])

In [60]:
np.linspace(3.,11.,50)

array([  3.        ,   3.16326531,   3.32653061,   3.48979592,
         3.65306122,   3.81632653,   3.97959184,   4.14285714,
         4.30612245,   4.46938776,   4.63265306,   4.79591837,
         4.95918367,   5.12244898,   5.28571429,   5.44897959,
         5.6122449 ,   5.7755102 ,   5.93877551,   6.10204082,
         6.26530612,   6.42857143,   6.59183673,   6.75510204,
         6.91836735,   7.08163265,   7.24489796,   7.40816327,
         7.57142857,   7.73469388,   7.89795918,   8.06122449,
         8.2244898 ,   8.3877551 ,   8.55102041,   8.71428571,
         8.87755102,   9.04081633,   9.20408163,   9.36734694,
         9.53061224,   9.69387755,   9.85714286,  10.02040816,
        10.18367347,  10.34693878,  10.51020408,  10.67346939,
        10.83673469,  11.        ])

In [63]:
np.logspace(3.,10.,50,endpoint=False)

array([  1.00000000e+03,   1.38038426e+03,   1.90546072e+03,
         2.63026799e+03,   3.63078055e+03,   5.01187234e+03,
         6.91830971e+03,   9.54992586e+03,   1.31825674e+04,
         1.81970086e+04,   2.51188643e+04,   3.46736850e+04,
         4.78630092e+04,   6.60693448e+04,   9.12010839e+04,
         1.25892541e+05,   1.73780083e+05,   2.39883292e+05,
         3.31131121e+05,   4.57088190e+05,   6.30957344e+05,
         8.70963590e+05,   1.20226443e+06,   1.65958691e+06,
         2.29086765e+06,   3.16227766e+06,   4.36515832e+06,
         6.02559586e+06,   8.31763771e+06,   1.14815362e+07,
         1.58489319e+07,   2.18776162e+07,   3.01995172e+07,
         4.16869383e+07,   5.75439937e+07,   7.94328235e+07,
         1.09647820e+08,   1.51356125e+08,   2.08929613e+08,
         2.88403150e+08,   3.98107171e+08,   5.49540874e+08,
         7.58577575e+08,   1.04712855e+09,   1.44543977e+09,
         1.99526231e+09,   2.75422870e+09,   3.80189396e+09,
         5.24807460e+09,

In [64]:
X = np.array([[ 0, 1, 2, 3], [ 4, 5, 6, 7], [ 8, 9, 10, 11]])
np.diag(X)

array([ 0,  5, 10])

In [65]:
X.diagonal()

array([ 0,  5, 10])

In [66]:
np.diagflat(X)

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  2,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  3,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  4,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  5,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  6,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  7,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  8,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  9,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 10,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 11]])

In [82]:
np.tri(3,5,-1)

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  0.,  0.,  0.]])

In [72]:
np.tri(3,5,0)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  0.,  0.]])

In [91]:
np.tril(np.arange(1,13).reshape(4,3),-1)

array([[ 0,  0,  0],
       [ 4,  0,  0],
       [ 7,  8,  0],
       [10, 11, 12]])

In [77]:
help(np.tri)

Help on function tri in module numpy.lib.twodim_base:

tri(N, M=None, k=0, dtype=<class 'float'>)
    An array with ones at and below the given diagonal and zeros elsewhere.
    
    Parameters
    ----------
    N : int
        Number of rows in the array.
    M : int, optional
        Number of columns in the array.
        By default, `M` is taken equal to `N`.
    k : int, optional
        The sub-diagonal at and below which the array is filled.
        `k` = 0 is the main diagonal, while `k` < 0 is below it,
        and `k` > 0 is above.  The default is 0.
    dtype : dtype, optional
        Data type of the returned array.  The default is float.
    
    Returns
    -------
    tri : ndarray of shape (N, M)
        Array with its lower triangle filled with ones and zero elsewhere;
        in other words ``T[i,j] == 1`` for ``i <= j + k``, 0 otherwise.
    
    Examples
    --------
    >>> np.tri(3, 5, 2, dtype=int)
    array([[1, 1, 1, 0, 0],
           [1, 1, 1, 1, 0],
        

In [78]:
help(np.tril)

Help on function tril in module numpy.lib.twodim_base:

tril(m, k=0)
    Lower triangle of an array.
    
    Return a copy of an array with elements above the `k`-th diagonal zeroed.
    
    Parameters
    ----------
    m : array_like, shape (M, N)
        Input array.
    k : int, optional
        Diagonal above which to zero elements.  `k = 0` (the default) is the
        main diagonal, `k < 0` is below it and `k > 0` is above.
    
    Returns
    -------
    tril : ndarray, shape (M, N)
        Lower triangle of `m`, of same shape and data-type as `m`.
    
    See Also
    --------
    triu : same thing, only for the upper triangle
    
    Examples
    --------
    >>> np.tril([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], -1)
    array([[ 0,  0,  0],
           [ 4,  0,  0],
           [ 7,  8,  0],
           [10, 11, 12]])



In [97]:
help(np.triu)

Help on function triu in module numpy.lib.twodim_base:

triu(m, k=0)
    Upper triangle of an array.
    
    Return a copy of a matrix with the elements below the `k`-th diagonal
    zeroed.
    
    Please refer to the documentation for `tril` for further details.
    
    See Also
    --------
    tril : lower triangle of an array
    
    Examples
    --------
    >>> np.triu([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], -1)
    array([[ 1,  2,  3],
           [ 4,  5,  6],
           [ 0,  8,  9],
           [ 0,  0, 12]])



In [98]:
np.triu(np.arange(1,13).reshape(4,3),-1)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 0,  8,  9],
       [ 0,  0, 12]])